### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by acxz** [golems/ach#10]
I can't seem to install ach even while following the installation instructions in the README.md. After having cloned the master branch, I go ahead and `autoreconf -i` and that fails with the following output:
```
doxygen.am:5: error: DX_COND_doc does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:11: error: DX_COND_html does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:21: error: DX_COND_chm does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:25: error: DX_COND_chi does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:37: error: DX_COND_man does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:47: error: DX_COND_rtf does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:57: error: DX_COND_xml does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:67: error: DX_COND_ps does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:96: error: DX_COND_pdf does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
doxygen.am:125: error: DX_COND_latex does not appear in AM_CONDITIONAL
Makefile.am:407:   'doxygen.am' included from here
autoreconf: automake failed with exit status: 1
```

If it is useful
OS: ArchLinux
autoconf: 2.69
master branch of ach
I also have doxygen installed.

**Comment by acxz** [comment]
I went ahead and commented out line 407 in Makefile.am and that fixes the issue as expected. The rest of the installation procedure executes flawlessly, besides the doxygen.am file.

**Comment by acxz** [comment]
Upon further investigation I found something similar and a fix to the issue: https://github.com/coldtobi/liblightify/commit/35355c128a844dec98b414c5
Not sure on how to fix it particularly for ach tho since there is also a doxygen latex target.

**Comment by acxz** [comment]
Using the previously linked commit I believe I fixed the autoconf process.
During `make`ing I also encountered an issue with the `man2html` command not generating the documentation, and fixed it by changing the call. `man2html` probably upgraded and deprecated some options. I went ahead and opened #11 with these fixes.

If @ndantam could take a look at it, would be much appreciated it!

**Comment by ndantam** [comment]
Doxygen issue reproduced on my system (Debian Stretch) and fixed by your PR.

I did not encounter the man2html problem (man2html version 1.6g-9), but removing the `-r` flag in your PR seems to work fine.

PR merged.  Thanks!
