### ISSUE TITLE
Make: achbench file missing

### ISSUE THREAD

**Issue by varunagrawal** [golems/ach#7]
When I run make after configuring the system as per the INSTALL instructions, I get the following error which breaks the build:

    help2man -h -h -v -V --no-info -n "benchmark and tune ach" ../achbench -o man/achbench.1
    help2man: can't get `-h' info from ../achbench
    Try `--no-discard-stderr' if option outputs to stderr

I looked through the project and can't find a achbench file. Can you please provide more details on the installation process and why the build is failing?

**Comment by ana-GT** [comment]
Varun,

Lines 92, 93 and 94 in ach/Makefile.am are the ones responsible for generating achbench. They are currently commented out. Can you try uncommenting them?  That way you will get the achbench binary (which is only a binary for testing - not needed for ach regular usage).

I just reproduced your error (which only appears if you install help2man). Doing the uncommenting above fixes it by now.

**Comment by ndantam** [comment]
Please try commit 892f1b9b315b2108aea24e07b6e419038daa3cb7

achbench was replaced by ipcbench.  I missed the manpage generation in the earlier commit.

**Comment by varunagrawal** [comment]
Still some errors present. Managed to find a fix. Will send Pull Request in a moment.
